Releasing with goreleaser
cloudposse/github-status-updater pull request #21
Opened 2023-04-08 06:41 UTC by zdmytriv

## what
* Releasing with `goreleaser` via `goreleaser/goreleaser-action`

## why
* Unified way of releasing GO packages

## references
- https://goreleaser.com/
- https://github.com/goreleaser/goreleaser-action

2023-04-08 12:37 UTC, osterman commented on .gitignore
>  .glide/
Delete all references to glide which we are deprecatingb

2023-04-09 18:01 UTC, Nuru requested changes, later dismissed
We already have `auto-release.yml`, so let's call the `goreleaser` workflow `build.yml` not `release.yml`

2023-04-09 18:01 UTC, Nuru commented on .github/workflows/release.yml
> +          go-version: '1.20'
Make sure version here matches version in `go.mod`:
https://github.com/cloudposse/github-status-updater/blob/0777ec94db59c864abe7d00f1d5149b3fd051034/go.mod#L3

Probably better to upgrade `go.mod` to 1.20, but then you need to update everything:
```
go mod edit -go 1.20
go get -u -t
go mod tidy -compat=1.20
```
and make sure it all still works.

2023-04-09 18:01 UTC, Nuru commented on .goreleaser.yaml
> +  name_template: 'checksums.txt'
```suggestion
builds:
  - env:
      # goreleaser does not work with CGO, it could also complicate
      # usage by users in CI/CD systems like Terraform Cloud where
      # they are unable to install libraries.
      - CGO_ENABLED=0
    mod_timestamp: '{{ .CommitTimestamp }}'
    goos:
      - darwin
      - freebsd
      - windows
      - linux
    goarch:
      - amd64
      - '386'
      - arm
      - arm64
    ldflags:
      # -s Omit the symbol table and debug information
      # -w Omit the DWARF symbol table
      # -X importpath.name=value # set the value of the string variable in importpath named name to value
      # Someday we could implement a "version" command and set the version like this:
      # - '-s -w -X "github.com/cloudposse/github-commenter/cmd.Version={{.Env.GORELEASER_CURRENT_TAG}}"'
      - '-s -w'

archives:
  - format: binary
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: sha256

release:
# If you want to manually examine the release before it is live, uncomment this line:
# draft: true

changelog:
  skip: true

```

2023-04-10 20:15 UTC, osterman commented on .github/workflows/release.yml
> +          go-version: '1.20'
We have standardized on calling all our release workflows `release.yml` everywhere.

2023-04-10 20:18 UTC, osterman commented on .github/workflows/release.yml
> +          go-version: '1.20'
Ok, I think I see what @Nuru is saying. This is using `goreleaser` to build. I think it should be called build.

2023-04-18 16:08 UTC, osterman approved these changes

2023-04-18 16:56 UTC, merged