Handle HTTPS_PROXY in http.Transport
cloudposse/github-status-updater pull request #22
Opened 2023-07-11 11:34 UTC by David-Crty

## what
* Adding the possibility to properly handle the HTTPS_PROXY env var

## why
* In some infra context the remote GitHub endpoint (eg: `api.github.com` is accessible only through a remote proxy)
* Currently if you set HTTPS_PROXY, the variable is ignored

## references
* Other PR that also tries to resolve this issue but has a conflict https://github.com/cloudposse/github-status-updater/pull/16 

Let me know if can do more to get this feature merged

2024-05-03 14:21 UTC, goruha requested changes

2024-05-03 14:21 UTC, goruha commented on main.go
> +	transport := &http.Transport{
@David-Crty are your sure this should be pointer ?

```suggestion
	transport := http.Transport{
```

2025-09-19 13:41 UTC, David-Crty commented
I have implemented the change, @goruha.

2026-05-08 05:06 UTC, David-Crty commented
No response so I will close this

2026-05-08 05:06 UTC, closed without merging